name: Daily Call
on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run my script
        run: python test_run.py
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add it_worked.txt
          git commit -m "Automated: it_worked file created"
          git push
