name: Daily Call
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add it_worked.txt
          git commit -m "Automated: it_worked file created"
          git push
